# Generated by Django 5.2.11 on 2026-02-14 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="checkpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cp_type", models.CharField(default="", max_length=50, unique=True)),
                ("serial_no", models.IntegerField(db_index=True, default=1)),
                ("cp_details", models.JSONField()),
                ("checkpoint_other_details", models.TextField(default="{}")),
                (
                    "last_modified_on",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
            ],
            options={
                "verbose_name": "Checkpoint",
                "verbose_name_plural": "Checkpoints",
                "db_table": "checkpoint",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=254, unique=True, verbose_name="user id"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=254, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=254, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "login_type",
                    models.CharField(
                        default="social", max_length=254, verbose_name="login type"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("other_details", models.JSONField(default=dict)),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "gmail_page_token",
                    models.CharField(
                        default="", max_length=254, verbose_name="Gmail Page Token"
                    ),
                ),
                (
                    "last_modified_on",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "customuser",
                "verbose_name_plural": "customusers",
            },
        ),
    ]
